### ISSUE TITLE
GA and Adwords linking shows clicks but no sessions/users

### ISSUE THREAD

**Issue by shazow** [googleanalytics/google-analytics-plugin-for-unity#106]
Hi, we're using GA through the Unity plugin and Adwords, which are linked. Campaigns are showing up in GA under Clicks, but all of the rows show 0 users and sessions (while impressions/clicks/cost/etc are all properly populated and in the thousands).

Linking seems to be fine, auto-tagging is enabled, what's going on? Are we missing something somewhere?

**Comment by baldwin628** [comment]
Did you add the CampaignTrackingReceiver and CampaignTrackingService to your manifest?

**Comment by shazow** [comment]
Heeeey thebaldwin! That might indeed have been the issue, pushing out a fixed build soon, will ping back if it doesn't help. :)
