### ISSUE TITLE
AdMob and Google Analytics packages conflict

### ISSUE THREAD

**Issue by andrew-grischenko** [googleanalytics/google-analytics-plugin-for-unity#142]
The problem: **Google Analytics and AdMob Unity packages, both from Google, are not compatible**
Unity 5.3, SDK 24

Steps:
1. Create new empty Unity project 
2. Install the [AdMob plugin](https://github.com/googleads/googleads-mobile-unity)
3. Install the Google Analytics plugin
4. Try to run project in Editor - get the error "Assets/PlayServicesResolver/Editor/GADependencies.cs(8,19): error CS0433: The imported type `Google.JarResolver.PlayServicesSupport' is defined multiple times"

Attempts to resolve the issue leads to issues further in building the package for Android with duplicated classes etc.  @baldwin628 You and @rampara need to sort it out, I could not find anyone solved that problem yet.

**Comment by rdaros** [comment]
@rampara @baldwin628 
Same problem here. Each plugin has its own JarResolver to do the same thing, causing conflicts. Any news on a possible fix or workaround?

**Comment by andrew-grischenko** [comment]
@rdaros 
This what worked for me:
1.Import the Google Analytics plugin first, delete the content in the Assets/PlayServicesResolver/ directory and then import the AdMob plugin.
2.Manually add Analytics as a Play services dependency via the code below. This code can be added to the AdMobDependencies.cs file or to a new file that declares Play services dependencies.

`Google.VersionHandler.InvokeInstanceMethod( svcSupport, "DependOn", new object[] { "com.google.android.gms", "play-services-analytics", "LATEST" }, namedArgs: new Dictionary<string, object>() { {"packageIds", new string[] { "extra-google-m2repository", "extra-android-m2repository"} } });`

3.If errors occur, exit Unity, remove all Play services AARs from the Assets/Plugins/Android directory of the project and remove the files "GoogleDependencyAdMobUnity.xml" and "GoogleAarExplodeCache.xml" in the "ProjectSettings" folder and restart of Unity.
5.Launch Unity and let Play Services Resolver re-import the appropriate files.
6.It should work after that.
