### ISSUE TITLE
Dose IOS plugins use HTTP?

### ISSUE THREAD

**Issue by SeereL** [googleanalytics/google-analytics-plugin-for-unity#144]
I just need to know whether IOS plugins use HTTPS instead of HTTP, if not, it may cause problem later.

**Comment by baldwin628** [comment]
Please see item 5 in the "v2.x to v3" section here:
https://developers.google.com/analytics/devguides/collection/ios/v3/migration

As long as you are not changing it, it should use the default value.

**Comment by SeereL** [comment]
OK, thank you
