### ISSUE TITLE
Display Advertising support 

### ISSUE THREAD

**Issue by mcungl** [googleanalytics/google-analytics-plugin-for-unity#16]
Is there a way to enable the "enableAdvertisingIdCollection" flag with this plugin?

Like described here
https://support.google.com/analytics/answer/2444872?hl=en

**Comment by paulgailey** [comment]
+1 for this feature please. With surge of Cardboard apps this is a must have.

**Comment by JavanAlucinaStudio** [comment]
Has this feature been implemented?
+1 if it hasn't been.

**Comment by quaidesapps** [comment]
+1

**Comment by coonmoo** [comment]
+1
any updates on this?
