### ISSUE TITLE
Name returned instead of SKU

### ISSUE THREAD

**Issue by nicolasjinchereau** [googleanalytics/google-analytics-plugin-for-unity#162]
https://github.com/googleanalytics/google-analytics-plugin-for-unity/blob/5a5caee6cc4a0188430ca65ea1c376288bca5fbf/source/Plugins/GoogleAnalyticsV4/HitBuilders/ItemHitBuilder.cs#L54-L56

**Comment by nicolasjinchereau** [comment]
https://github.com/googleanalytics/google-analytics-plugin-for-unity/pull/163

**Comment by baldwin628** [comment]
Thanks for the fix.
