### ISSUE TITLE
Google Analytics Unity Plugin for Windows app

### ISSUE THREAD

**Issue by himanshuajmera** [googleanalytics/google-analytics-plugin-for-unity#180]
Hi Everyone,
I'm a game developer and I'm building a VR based game which will be running on windows platform (.exe). Does Google Analytics Unity Plugin windows platform as well? I checked the documentation but there were no configuration instructions for windows.
Please let me know asap. If you have other options in your mind please share. Not Unity Analytics, it's slow.

**Comment by JcFowles** [comment]
Hi @himanshuajmera did find a solution to this? 

I am also wanting to use google analytics for a windows desktop application. The application will be used on very limited number of pc ( to my knowledge just 2). 

It will be used at an expo type event, and I would like to track a number of things during that event 
ie number of users, time user spent on app, what levels were completed, etc

**Comment by himanshuajmera** [comment]
Hi @JcFowles ,
The answer is yes. My application is live and Google Analytics is working well with it.

Also, I'm closing this issue as we have the answer now.

**Comment by JcFowles** [comment]
@himanshuajmera  Awesome, sorry for the follow up. 

But may I ask how you set it up? 
On the google analytics site the only options are website and mobile app. (which did you use?) and if its mobile it uses firebase now which also only supports Ios and Android.

**Comment by himanshuajmera** [comment]
It's same as how you will do it for website. Just download GAv4 plugin and in your application manager script import GoogleAnalytics Library. And configure it as shown in documentation.

**Comment by JcFowles** [comment]
@himanshuajmera 
Awesome thank you very much
