### ISSUE TITLE
Error building Player: ArgumentNullException: Argument cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by fliperamma** [googleanalytics/google-analytics-plugin-for-unity#36]
I was getting this error (Error building Player: ArgumentNullException: Argument cannot be null. Parameter name: key) when trying to build for iOS (Unity PRO 4.6.3f1 and Xcode 6.1.1 / OSX 10.9.5).
I managed to "solve" the error after removing Google Analytics Plugin so - maybe - it's related to Google Analytics Plugin.
Maybe this solution : http://visionpunk.vanillaforums.com/discussion/1056/error-after-unity-install will help to find the error (if there's one)

Thanks

Fabio

**Comment by fliperamma** [comment]
I'm having the same issue again so the bug it's probably not related to Google Analytics plugin

**Comment by baldwin628** [comment]
Closing this as it sounds like its unrelated to the plugin.
