### ISSUE TITLE
EntryPointNotFoundException: setDispatchInterval

### ISSUE THREAD

**Issue by SafronSG** [googleanalytics/google-analytics-plugin-for-unity#38]
I get this exception with every event. But in GAv3 prefab dispatch period set 5.
Also I tried set dispatch period in script, but it didn't help:
```C#
try
{
        googleAnalytics.dispatchPeriod = 20;
        googleAnalytics.DispatchHits();
}
catch (Exception ex)
{
	Debug.Log("DispatchPeriod" + googleAnalytics.dispatchPeriod +  " EXCEPTION: " + ex.Message);
}
```
Plugin perfect work in Android, but crash iOS Simulator

**Comment by baldwin628** [comment]
If you are compiling using mono, Unity wraps plugin methods with:
```
#if !(TARGET_IPHONE_SIMULATOR)
```
You can try compiling using il2cpp or edit the RegisterMonoModules.cpp file and move the 
```
mono_dl_register_symbol
```
method declaration and subsequent calls outside of the #if blocks.
