### ISSUE TITLE
iOS link attributing don't work

### ISSUE THREAD

**Issue by BestStream** [googleanalytics/google-analytics-plugin-for-unity#40]
I tryed to attributing iOS link like this
https://www.youtube.com/watch?v=K5gNZP6IqEk
https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns-update#url-builder

But it's don't work. I can't see install's source in analytics. In case of Google Play attributing works well

**Comment by baldwin628** [comment]
Unfortunately this won't work at the moment without IDFA support.  This is high on our list to support in the plugin.

**Comment by BestStream** [comment]
Really looking forward!
