### ISSUE TITLE
Application.RegisterLogCallback is deprecated in 5.0

### ISSUE THREAD

**Issue by BTooLs** [googleanalytics/google-analytics-plugin-for-unity#43]
Hello,

I'm using Unity 5.0.0.0f4

I got this warning:
> Assets/Plugins/GoogleAnalyticsV3/GoogleAnalyticsV3.cs(121,29): warning CS0618: `UnityEngine.Application.RegisterLogCallback(UnityEngine.Application.LogCallback)' is obsolete: `Application.RegisterLogCallback is deprecated. Use Application.logMessageReceived instead.'

**Comment by georgepiva** [comment]
Same warning here.

**Comment by borrrden** [comment]
In the official release it seems to be missing altogether.  Is there a replacement?

**Comment by BTooLs** [comment]
The warning says " Use Application.logMessageReceived instead.'"

And the documentation is not updated
http://feedback.unity3d.com/suggestions/unity-5-beta-urgently-needs-api-changes-documented

That's all I know.

/********************************
@author *B.G. Adrian*
@as *Game developer*
@from www.*btools*.eu
@games www.*bcardgames.com*
@work www.*mavenhut*.com
*********************************/

**Comment by baldwin628** [comment]
This should be fixed in the latest version, thanks for the detailed info.
