### ISSUE TITLE
Warnings about "rejected withstatus code HTTP/2.0 200 OK" etc

### ISSUE THREAD

**Issue by coquifrogs** [googleanalytics/google-analytics-plugin-for-unity#46]
In a Unity 4.6.4 Web Player build, we're getting various warning messages depending on browser that state things like:

"Google Analytics hit request rejected withstatus code HTTP/2.0 200 OK"
"Google Analytics hit request rejected withstatus code 200 OK"

I'm assuming these are actually accepted, but the the "STATUS" header value is not exactly matching "HTTP/1.1 200 OK" so it is warning about it.

**Comment by coquifrogs** [comment]
Relevant Debug.Log statements are in GoogleAnalyticsMPV3.cs in HandleWWW.

**Comment by baldwin628** [comment]
Thanks for the fix!
