### ISSUE TITLE
Only Wifi Works

### ISSUE THREAD

**Issue by aymericgeffroy** [googleanalytics/google-analytics-plugin-for-unity#49]
Hello,

When i turn on wifi connection, the data will send to googleanalytics realtime, but when i turn off, i can see messages in logcat that message sent but nothing in googleanalytics realtime.
If I copy/past URL in googechrome on device, the data will be send to googleanalytics realtime.

Who can help me ?

<code>

  \<uses-permission android:name="android.permission.INTERNET"/>

  \<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

</code>

Thanks.
Aymeric

**Comment by eppz** [comment]
Just submitted the same issue.
Maybe some Unity reachability issue?
Other WWW calls - like the snippet here http://docs.unity3d.com/ScriptReference/WWW.html - just doing fine.

Did you progress on this issue?

**Comment by eppz** [comment]
https://github.com/googleanalytics/google-analytics-plugin-for-unity/issues/50

**Comment by aymericgeffroy** [comment]
Maybe due to poor internet connexion for me.
