### ISSUE TITLE
RealTime not works from Editor (but works fine with pasted url from console)

### ISSUE THREAD

**Issue by eppz** [googleanalytics/google-analytics-plugin-for-unity#50]
Hi,
hooked up everything from the Docs (manifest, properties, verbose logging, no dry run, singletons don't get destoryed, etc..), but I can't see any hit from the Unity Editor (play mode).

I put the full measurement protocol URL that is to be sent, even the coroutine returns with success, but no hit registered real time.

When I simply copy the URL into my browser, real time hit immediately show, like it always did using iOS / Web SDK.

Is there any minor detail I missed?

**Comment by eppz** [comment]
I had some "leftover" scripts from GameAnalytics SDK. After removing them the issue just gone. Did not resolved the exact file, though.

**Comment by baldwin628** [comment]
It sounds like you resolved it, if not, feel free to reopen this.
