### ISSUE TITLE
Unity3D idfa problem (not work)

### ISSUE THREAD

**Issue by DziD** [googleanalytics/google-analytics-plugin-for-unity#68]
In description says: The SDK will now collect IDFA and the advertiser tracking enabled flag if the library libAdIdAccess.a (provided as part of the SDK) is included in the application and the allowIDFACollection property is set to true on the tracker.

But it not TRUE!!!

If on Android it works (yes, on Android it works), then on iOS it doesn't work (google analytics not see idfa from my application)

**Comment by baldwin628** [comment]
Can you provide the console logs in a gist from xcode.
