### ISSUE TITLE
V4, Android - ClassNotFoundException : com.google.android.gms.analytics.GoogleAnalytics

### ISSUE THREAD

**Issue by Dragonic89** [googleanalytics/google-analytics-plugin-for-unity#86]
Hello,

I'm using the package V4 with Unity 5.1.3 f1 !

No problem when tested within Unity Editor, can send hits and I can see them on my Analytics account real time overview !

On Android device after APK build, I have this error when I call StartSession() :
> ClassNotFoundException : com.google.android.gms.analytics.GoogleAnalytics

Test on Galaxy S2 Android 4.1.2 and Archos 101d Neon Android 4.4, same error.
(Google Play Service up to date on devices and in my android SDK setup, build-tools also)

Also tried to include the PlayGame Service plugin for Unity (v0.9.26) because of this topic : http://stackoverflow.com/questions/27125774/gms-analytics-googleanalytics-noclassdeffounderror
But same error on device.

Did I miss something ? (V3 with same setup is working)

**Comment by baldwin628** [comment]
Did you copy play services into your Unity project?  See the setup option in the top menu under Google Analytics.

**Comment by Dragonic89** [comment]
Thank you balwin628, I didn't notice the setup menu, maybe because there isn't one in V3 !
I tried the play services from this github : https://github.com/playgameservices/play-games-plugin-for-unity
That's why this does not work !

After the setup everything is now working on device ^^ !

Thank you, I'm closing this topic !
