### ISSUE TITLE
Google not serving crossdomain.xml file for web player tracking.

### ISSUE THREAD

**Issue by shochet** [googleanalytics/google-analytics-plugin-for-unity#9]
When trying to send a tracking event from the editor or web player, I get the following WWW error:
Google Analytics hit request failed with error Rejected because no crossdomain.xml policy file was found

Shouldn't Google be serving a crossdomain.xml file in their web root per the Unity security model:
http://docs.unity3d.com/Manual/SecuritySandbox.html

Not a problem on iOS.

**Comment by aaronflippo** [comment]
Just adding my two cents that web player support would greatly benefit us as well.
We've been using a separate piece of code that's a couple years old (I can't remember where I found it!) and I believe it gets around the crossdomain.xml sandboxing, by using "externalEval" to execute javascript snippets on the enclosing webpage - so technically it's the browser making the request to GA. I should also mention that the code we're using interacts with GA as a web page, not a mobile app.

Regarding plugins in the web player: "managed" plugins such as NGUI can work in a browser, but not natively compiled plugins.

**Comment by dspattison-google** [comment]
https://www.google-analytics.com/crossdomain.xml is live
