### ISSUE TITLE
BundleID and ProductName should be taken from the runtime Application class

### ISSUE THREAD

**Issue by AdriaandeJongh** [googleanalytics/google-analytics-plugin-for-unity#97]
With different bundle identifiers and localised product names, it's more than annoying that I have to set the BundleID, ProductName, and BundleVersion variables every time I compile for a different target. Instead of variables, both BundleID and ProductName currently have runtime variables that can and should be used instead:

http://docs.unity3d.com/ScriptReference/Application-bundleIdentifier.html
http://docs.unity3d.com/ScriptReference/Application-productName.html

There is currently no way to get the bundle version at runtime (which is stupid on Unity's behalf), but that should ideally also come from the PlayerSettings instead of having to be set manually on the GoogleAnalytics prefab.

**Comment by adrianmavenhut** [comment]
Yes is annoing, we had to modify the GA C# class so it takes the codes from our config files, including name/version.

**Comment by BTooLs** [comment]
Yes is annoing, we had to slighty alter the GA C# class so it takes the params from our config files, at runtime.

**Comment by belm0** [comment]
This cannot be done blindly in the case of BundleID.  In standalone targets, Application.bundleIdentifier is not user defined, but rather identifies the unity build itself.  That's not suitable for Analytics API bundleID, which maps to the "App ID" in the Analytics service.  App ID should identify my app, not unity.

**Comment by raldred** [comment]
We've implemented it ourselves, it would be easy to make this a mobile specific patch using:

    #if !UNITY_EDITOR && (UNITY_IOS || UNITY_ANDROID)
