### ISSUE TITLE
Ecommerce Transactions Tracking

### ISSUE THREAD

**Issue by cbothra** [googleanalytics/google-analytics-plugin-for-unity#98]
I have successfully integrated GAV4 in my project and got it working. I am also using GoogleAnalytics in order to track the real money transactions in my project. 
The issue I am facing is that sometimes I made the purchases and didn't got the events for the same. So basically I wanted to know if it drops those Ecommerce tracking events? Also I wanted to know whats the delay after which I shall expect the events in the dashboard?

Thanks-in-Advance.

**Comment by kenglou** [comment]
Previously I found that GAV4 doesn't implement the Ecommerce Transactions. Is that implemented already now? If there is still no implementation on that I might think of dropping use of GAV in my games.

Thank you.

**Comment by cbothra** [comment]
Hi I believe it does as per following documentation link:
https://developers.google.com/analytics/devguides/collection/unity/v3/reference

Can you provide me the link where you found that its not available?

Thanks

**Comment by kenglou** [comment]
the link you provided are for GAV3, if you look carefully on the Ecommerce Tracking Event classes, you might found that it is not implemented and left empty. But that is from what i found previously and I think the code might change a bit more(I'm not sure on current one). So feel free to check it out and tell me if it is implemented.

Thank you.

**Comment by shazow** [comment]
@baldwin628 Any idea what the status is on this?

**Comment by cbothra** [comment]
Hi baldwin628,
I am pretty sure that something is broken in analytics library itself. I am using it and its not reliable. It doesn't provide details of each IAP but sometimes it does. So overall it looks to me like there is no issue in the sdk implementation. I believe that user is failing to capture the event.

**Comment by xuyennguyen** [comment]
Hello guys,
I integrated GV4 into my project. I also used LogItem and LogTransastion to track the real money transactions.  I sent to event and seem like okay but when I checked on google analytics, I didn't see any data on this site. I don't why. I am using unity plugin.
Here the code I sent

```
[googleAnalytics.LogItem (new ItemHitBuilder ()
								.SetTransactionID ("1234")
								.SetName ("IAP:" + packName)
								.SetSKU (packName)
								.SetCategory ("IAP")
								.SetPrice (price)
								.SetQuantity (1)
								.SetCurrencyCode (currencyCode)
		
			);
			googleAnalytics.LogTransaction (new TransactionHitBuilder ()
								.SetTransactionID ("1234")
								.SetAffiliation ("IAP store")
								.SetRevenue (price)
								.SetTax (0.0)
								.SetShipping (0.0)
								.SetCurrencyCode (currencyCode));
			
		}
]
[```](http://www.upsieutoc.com/image/YUrI)

**Comment by baldwin628** [comment]
@xuyennguyen
For v4, ecommerce isn't implemented yet.

@cbothra can you provide more details as to how you have it setup and the conditions where you see this happening. Also, do you know if it's specific users or a specific type of transaction?

**Comment by shazow** [comment]
@baldwin628 Any idea where the lacking implementation is? I was looking through the code and I didn't find anything ecommerce-related missing compared to v3.

**Comment by baldwin628** [comment]
@shazow Logitem, Logtransaction methods in the Android files.

**Comment by shazow** [comment]
@baldwin628 Where can I get these Android files? There's a jar with the built .class files but I don't think you want me to patch those. :) Is the .java source up somewhere?

**Comment by baldwin628** [comment]
@shazow I mean the ones in the repo here:

https://github.com/googleanalytics/google-analytics-plugin-for-unity/blob/master/source/Plugins/GoogleAnalyticsV4/GoogleAnalyticsAndroidV4.cs#L110

**Comment by shazow** [comment]
Aaaaaaaaah thanks, I'll take a look.

**Comment by shazow** [comment]
Are there any implications if we used the GoogleAnalyticsMPV3 tracker (native C#) rather than the Android (Java) handlers for that subset of functionality? Any idea if there would be notable performance/blocking implications for apps? ([Related StackOverflow](http://stackoverflow.com/a/35510780/187878))
